services:
  postgres:
    image: postgres:17
    container_name: postgres-tryton-v80
    environment:
      - POSTGRES_USER=tryton
      - POSTGRES_PASSWORD=tryton
      - POSTGRES_DB=tryton80
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tryton_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tryton -d tryton80"]
      interval: 10s
      timeout: 5s
      retries: 5

  trytond-v80:
    container_name: trytond-v80
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./modules/:/tmp/modules
      - ./trytond.conf:/etc/trytond.conf
      - ./sao:/var/www/sao
    ports:
      - "8000:8000"  # Cambiado a 8000 que es el puerto por defecto de Tryton
    environment:
      - TRYTOND_CONFIG=/etc/trytond.conf
      # Variables de conexión a PostgreSQL
      - DB_HOSTNAME=postgres
      - DB_HOST
      - DB_PORT=5432
      - DB_NAME=tryton80
      - DB_USER=tryton
      - DB_PASSWORD=tryton
      - TRYTON_DATABASE=tryton80
      - MODULE_PREFIXES=padulles_
    networks:
      - tryton_network
    depends_on:
      postgres:
        condition: service_healthy  # Espera a que PostgreSQL esté saludable
    command: trytond

networks:
  tryton_network:
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data_trytond