version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres-tryton-v80
    environment:
      - POSTGRES_USER=tryton
      - POSTGRES_PASSWORD=tryton
      - POSTGRES_DB=tryton80
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tryton_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tryton -d tryton80"]
      interval: 10s
      timeout: 5s
      retries: 5

  trytond-v80-1:
    container_name: trytond-v80-1
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./modules/:/tmp/modules
      - ./trytond.conf:/etc/trytond.conf
      - ./sao:/var/www/sao
    environment:
      - TRYTOND_CONFIG=/etc/trytond.conf
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tryton80
      - DB_USER=tryton
      - DB_PASSWORD=tryton
      - TRYTON_DATABASE=tryton80
      - MODULE_PREFIXES=padulles_
    networks:
      - tryton_network
    depends_on:
      - postgres
    command: trytond

  trytond-v80-2:
    container_name: trytond-v80-2
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./modules/:/tmp/modules
      - ./trytond.conf:/etc/trytond.conf
      - ./sao:/var/www/sao
    environment:
      - TRYTOND_CONFIG=/etc/trytond.conf
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tryton80
      - DB_USER=tryton
      - DB_PASSWORD=tryton
      - TRYTON_DATABASE=tryton80
      - MODULE_PREFIXES=padulles_
    networks:
      - tryton_network
    depends_on:
      - postgres
    command: trytond

  trytond-v80-3:
    container_name: trytond-v80-3
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./modules/:/tmp/modules
      - ./trytond.conf:/etc/trytond.conf
      - ./sao:/var/www/sao
    environment:
      - TRYTOND_CONFIG=/etc/trytond.conf
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tryton80
      - DB_USER=tryton
      - DB_PASSWORD=tryton
      - TRYTON_DATABASE=tryton80
      - MODULE_PREFIXES=padulles_
    networks:
      - tryton_network
    depends_on:
      - postgres
    command: trytond

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-sao
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./sao:/var/www/sao:ro
    ports:
      - "80:80"
    depends_on:
      - trytond-v80-1
      - trytond-v80-2
      - trytond-v80-3
    networks:
      - tryton_network

networks:
  tryton_network:
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data_trytond
