version: '3.8'

networks:
  red_trytond-70:
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/24

services:
  trytond-v70:
    image: tryton/trytond:7.0
    container_name: trytond-v70
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      red_trytond-70:
        ipv4_address: 192.168.101.10
    volumes:
      - ./modules/:/tmp/modules
      - ./modules_ar/:/tmp/modules_ar
      - ./trytond.conf:/etc/trytond.conf
    environment:
      - TRYTOND_CONFIG="/etc/trytond.conf"
    command: 
      ["gunicorn", "-w", "1", "-b", "0.0.0.0:8000", "trytond-app"]
  
  trytond_worker-v70:
    image: tryton/trytond:7.0
    container_name: trytond_worker-v70
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      red_trytond-70:
        ipv4_address: 192.168.101.11
    volumes:
      - ./modules/:/tmp/modules
      - ./modules_ar/:/tmp/modules_ar
      - ./trytond.conf:/etc/trytond.conf
    environment:
      - TRYTOND_CONFIG
      - TRYTOND_DB
    command:
      ["trytond-worker", "-d", "${TRYTOND_DB}"]

  trytond-cron-v70:
    image: tryton/trytond:7.0
    container_name: trytond-cron-v70
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      red_trytond-70:
        ipv4_address: 192.168.101.12
    volumes:
      - ./modules/:/tmp/modules
      - ./modules_ar/:/tmp/modules_ar
      - ./trytond.conf:/etc/trytond.conf
    environment:
      - TRYTOND_CONFIG
      - TRYTOND_DB
    command: 
      ["trytond-cron", "-d", "${TRYTOND_DB}"]

  nginx-sao-v70:
    image: nginx:stable
    container_name: nginx-sao-v70
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./sao:/var/www/sao
    ports:
      - "8080:80"
    networks:
      red_trytond-70:
        ipv4_address: 192.168.101.13
    depends_on:
      - trytond-v70


