server {
    listen 80;
    server_name localhost;

    root /var/www/sao;

    location /static/ {
        alias /var/www/sao/;
        try_files $uri $uri/ =404;
    }

    location / {

        if ($request_method = POST) {
            proxy_pass http://trytond-v70:8000; 
            break;                                                            
        }

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 5400s;
        proxy_connect_timeout 5400s;
        proxy_send_timeout 5400s;
    }
}