[jsonrpc]
listen=0.0.0.0:8000
#data=/var/www/localhost/tryton

#[xmlrpc]
#listen=*:8069

[database]
# uri=postgis://trytond:trytond@localhost:5432
uri=postgresql://trytond:trytond@host.docker.internal:5432
path=/opt/trytond/data
#language=es
subquery_threshold=200

#[ssl]
#certificate=/etc/ssl/certs/nginx-selfsigned.crt
#privatekey=/etc/ssl/private/nginx-selfsigned.key

[email]
uri=smtps://pablopadulles:oqcarmqvxntfeqxw@smtp.gmail.com:465
from=pablopadulles@gmail.com
#uri=smtps://usuario:password@smtp.dominio.com:465
#from=usuario@dominio.com

[session]
max_age=86400
timeout=3600
authentications=ldaphnap,password
#super_pwd=ULL5.TjOORr7o

#~ [report]
#~ unoconv=pipe,name=trytond;urp;StarOffice.ComponentContext

[web]
# root = /home/pablo/desarrollo/tryton/7.0/sao
root = /var/wwww/sao
listen=*:8001
email_validation_url=http://localhost:5000/api/email_validation
reset_password_url=http://localhost:5000/api/reset_password

#[bus]
#allow_subscribe = True
#long_polling_timeout = 20
#cache_timeout = 20

[password]
entropy=0

[request]
max_size_authenticated=0
max_size=0

# [attachment]
# filestore=True
# ImageGalery=ImageGalery

[queue]
worker=False

# [ldap_authentication]
# uri=ldaps://local.hospitalposadas.gob.ar/CN=API LDAP,OU=Application,OU=Users Accounts,DC=local,DC=hospitalposadas,DC=gob,DC=ar
# bind_pass=4P1_$d4p.24
# uid=sAMAccountName
# create_user=True
# active_directory=True
# scope=subtree

[ldap_hnap]
uri=http://10.5.0.124:8000/login/
create_user=True
uid=samaccountname