[database]
uri = postgresql://tryton:tryton@postgres:5432
path = /opt/trytond/data
# Importante para que el front vea las bases disponibles
list = True
subquery_threshold = 200

[session]
max_age = 86400
timeout = 3600
# Asegúrate de que estos métodos de auth estén bien configurados
authentications = password

[web]
# Esta es la ruta donde están los archivos de SAO v8.0
root = /var/www/sao
# listen = 0.0.0.0:8000
listen = *:8000
# Si vas a usar SAO desde otro puerto o dominio, activa cors:
cors = *
# Necesario para manejar correctamente las rutas rpc detrás de Werkzeug
num_proxies = 1

[email]
uri = smtps://pablopadulles:oqcarmqvxntfeqxw@smtp.gmail.com:465
from = pablopadulles@gmail.com

[password]
entropy = 0

[request]
# Es mejor poner límites razonables que 0 (ilimitado) para evitar ataques DoS, 
# pero lo mantengo como lo tenías:
max_size_authenticated = 2147483648
max_size = 2097152

[queue]
worker = False