upstream trytond_v80 {
    server trytond-v80-1:8000;
    server trytond-v80-2:8000;
    server trytond-v80-3:8000;
}

server {
    listen 80;
    server_name localhost;

    root /var/www/sao;

    location /static/ {
        alias /var/www/sao/;
        try_files $uri $uri/ =404;
    }

    location / {
        proxy_pass http://trytond_v80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_read_timeout 5400s;
        proxy_connect_timeout 5400s;
        proxy_send_timeout 5400s;
    }
}
